name: Create Environment-Specific Artifact

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - Development
          - Production

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use environment-specific secret in artifact
        env:
          SECRET_CONNECTION_STRING: ${{ secrets.ConnectionString }}
        run: |
          echo "Environment-specific secret value is $SECRET_CONNECTION_STRING" > appSettings.config

      - name: Zip all files
        run: |
          zip -r files.zip ./

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-secret-artifact-${{ github.event.inputs.env }}
          path: files.zip
